In [ ]:
# 2.0. Set up Librairies

In [1]:
import numpy as np
import pandas as pd

In [3]:
# 2.1. Télécharger le fichier csv et l'ouvrir sur ton notebook

In [13]:
museums = pd.read_csv('/Users/juliensisavath2017/THP_loc/THP-2/S04/2/Project/1.Tour_de_France_des_musees/data.csv', sep = ";", encoding = 'latin-1')

In [43]:
museums

,osm_id,name,number,street,postal_code,city,country,country_code,lat,lon,website,email,phone,fax,tags,description,date_added,wikidata
0,4540234591,3 bis f,109,Avenue du Petit Barthélémy,13617.0,Aix-en-Provence,France,fr,43.521207,5.439875,http://www.3bisf.com,contact@3bisf.com,3.344216e+10,NaN,osm:museum;art:art contemporain,NaN,"44116,0076388889",NaN
1,4388745689,A casa di Losari,NaN,T 30,20226.0,Belgodère,France,fr,42.638732,9.007660,NaN,NaN,NaN,NaN,osm:museum,NaN,"43338,9393981481",NaN
2,4426176194,À l'homme volant,35,Grande Rue,72300.0,Sablé-sur-Sarthe,France,fr,47.839656,-0.334043,NaN,NaN,3.324395e+10,NaN,osm:museum;type:centre d'interpretation,NaN,"42644,4636574074",NaN
3,7652598615,Abbadiale - Maison des arts,NaN,Rue du Gabizos,65400.0,Arras-en-Lavedan,France,fr,42.990826,-0.128057,https://www.abbadiale.fr/,NaN,3.363317e+10,NaN,osm:museum,NaN,"44120,0466782407",NaN
4,121580330,Abbaye,NaN,Rue de l'Abbaye,39210.0,Château-Chalon,France,fr,46.753866,5.624296,NaN,NaN,NaN,NaN,osm:museum;art:architecture,NaN,"43102,5491898148",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3779,1348524503,Vivarium du Moulin,NaN,Rue Principale,68610.0,Thann-Guebwiller,France,fr,47.942258,7.149613,NaN,NaN,NaN,NaN,osm:museum,NaN,"40747,8717476852",NaN
3780,577287841,Voyage au Temps des impressionnistes,NaN,Rue de Léry,95430.0,Auvers-sur-Oise,France,fr,49.072057,2.166167,NaN,NaN,NaN,NaN,osm:museum,NaN,"41141,7272222222",NaN
3781,145062184,Wines and Spirits Museum,NaN,Corniche Bonaparte,83150.0,Bandol,France,fr,43.128031,5.749484,NaN,NaN,NaN,NaN,osm:museum,NaN,"42367,7135069444",NaN
3782,82988725,Xanxotea,NaN,La Place,64240.0,Isturits,France,fr,43.364834,-1.203580,http://www.xanxotea.com/,NaN,NaN,NaN,osm:museum,Musée ethnographique Xanxotea pour découvrir l...,"44129,580775463",NaN
3783,277107550,Xylotheque - Kiosque Pedagogique,NaN,Impasse de la Haie Vive,45590.0,Saint-Cyr-en-Val,France,fr,47.825888,1.967795,NaN,NaN,NaN,NaN,osm:museum,NaN,"43331,4758449074",NaN

In [ ]:
# 2.1. Télécharger le fichier csv et l'ouvrir sur ton notebook

In [ ]:
## Combien y-a-t-il de musées en France métropolitaine ?

In [14]:
museums.size

68112

In [ ]:
## Dans quelle(s) ville(s) y-a-t-il de plus de musées ?
## Quel est le nombre moyen de musées par ville ?
## Quel est le nombre médian de musées par ville ?
## Comment sont répartis les musées par type (en pourcentage) ?

In [53]:
museums.describe(include="all")

,osm_id,name,number,street,postal_code,city,country,country_code,lat,lon,website,email,phone,fax,tags,description,date_added,wikidata
count,3.784000e+03,3784,743,3771,3728.000000,3782,3784,3784,3784.000000,3784.000000,1636,301,1.211000e+03,0.0,3782,226,3775,1147
unique,NaN,3466,197,2932,NaN,2295,2,2,NaN,NaN,1585,295,NaN,NaN,119,206,3331,1133
top,NaN,Musée des Beaux-Arts,1,Grande Rue,NaN,Paris,France,fr,NaN,NaN,http://www.ville-orleans.fr,musees@ville.angers.fr,NaN,NaN,osm:museum,Ecomusée,"43940,5848958333",Q16010845
freq,NaN,23,73,34,NaN,175,3776,3776,NaN,NaN,4,3,NaN,NaN,2175,19,76,2
mean,2.193306e+09,NaN,NaN,NaN,48499.273069,NaN,NaN,NaN,46.531075,2.724237,NaN,NaN,3.637847e+10,NaN,NaN,NaN,NaN,NaN
std,2.521168e+09,NaN,NaN,NaN,27982.341434,NaN,NaN,NaN,2.234572,2.897485,NaN,NaN,9.501361e+10,NaN,NaN,NaN,NaN,NaN
min,5.107373e+06,NaN,NaN,NaN,1000.000000,NaN,NaN,NaN,41.498794,-5.129406,NaN,NaN,8.250029e+08,NaN,NaN,NaN,NaN,NaN
25%,1.451896e+08,NaN,NaN,NaN,25582.500000,NaN,NaN,NaN,44.542494,0.570318,NaN,NaN,3.325117e+10,NaN,NaN,NaN,NaN,NaN
50%,8.226927e+08,NaN,NaN,NaN,49730.000000,NaN,NaN,NaN,46.513252,2.563655,NaN,NaN,3.338552e+10,NaN,NaN,NaN,NaN,NaN
75%,3.982632e+09,NaN,NaN,NaN,71570.000000,NaN,NaN,NaN,48.639156,4.984839,NaN,NaN,3.349082e+10,NaN,NaN,NaN,NaN,NaN
max,8.394269e+09,NaN,NaN,NaN,590007.000000,NaN,NaN,NaN,51.053756,9.488302,NaN,NaN,3.320256e+12,NaN,NaN,NaN,NaN,NaN

In [ ]:
## Combien y-a-t-il de musées dont le nom commence par "Château" ?

In [ ]:
## Pour combien de musées dispose-t-on de l'adresse du site web ?

In [ ]:
## Quel département français possède le plus de musées sur son territoire ?

In [ ]:
## Quel département français possède le moins de musées sur son territoire ?

In [ ]:
## Combien de musées ont "Napoléon" dans leur nom ?

In [ ]:
# 2.3. Proposer deux axes d'analyse supplémentaires

In [ ]:
## Un site qui donne la fréquentation de tous les musées français

In [ ]:
[Fréquentation des musées de France](https://data.culture.gouv.fr/explore/dataset/frequentation-des-musees-de-france/information/)

In [ ]:
## Qui visite les musées

In [ ]:
[Qui visite les musées](https://doc.ocim.fr/LO/LO035/LO.35%284%29-pp.16-23.pdf)